"""Seed the supply catalog with items from the Square catalog export."""

import logging

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.supply_catalog import SupplyItem

logger = logging.getLogger(__name__)

CATALOG_ITEMS = [
    {"name": "1 DOLLAR PACK", "category": "Coins And Cash", "description": "$20 ONES", "price": 20.0, "square_token": "VMFB4LWVAB3ATK5UBUTDWJD6"},
    {"name": "12 OZ WHITE FOOD CONTAINERS", "category": "Bakery Only", "description": "1 Case", "price": 69.86, "square_token": "OUESTWYB2S4LHNUAMDWFFJWN"},
    {"name": "2% MILK (Case of 6)", "category": "Food And Milks", "description": "CASE OF 6 - 1 GAL", "price": 32.38, "square_token": "SOOGZC64ZUWGKX6QGJVDK5PG"},
    {"name": "5 DOLLAR PACK", "category": "Coins And Cash", "description": "$20 IN $5s", "price": 20.0, "square_token": "7GGU3XVDJB55R4SPF4MY6IXG"},
    {"name": "50 LB. BAG OF SUGAR", "category": "Bakery Only", "description": "Bag", "price": 35.0, "square_token": "AGWOLLPBJ5Y56N453FIUFCRL"},
    {"name": "ALMOND FLOUR (BAKERY)", "category": "Bakery Only", "description": "5LBS", "price": 30.57, "square_token": "ZLBOWGVHBT3X5BXISUTXRI6D"},
    {"name": "ALMOND MILK", "category": "Food And Milks", "description": "Case 6 half gallons", "price": 40.12, "square_token": "EIK4U2HICRCL3BQKHEMEY2ZL"},
    {"name": "ALMOND POPPY BREAD", "category": "Food And Milks", "description": "Loaf", "price": 18.0, "square_token": "6PGQT6AUGTH7FQXSJ6P6WRSQ"},
    {"name": "ALMONDS (BAKERY)", "category": "Bakery Only", "description": "1 BAG", "price": 30.57, "square_token": "OJADMYFFLL36ETNZZMTM4NJP"},
    {"name": "APPLE JUICE", "category": "Food And Milks", "description": "CASE OF 8 - 64oz", "price": 35.49, "square_token": "LDWALNDOAVDQUQJMUXDYWNNV"},
    {"name": "Apron", "category": "Merchandise", "description": "1 apron", "price": 17.06, "square_token": "5IKEAGASSKME2XB7O4DT66Q4"},
    {"name": "BACON SLICED (BAKERY)", "category": "Bakery Only", "description": "Case", "price": 48.95, "square_token": "PM3X3UIRVGBQ73P2676MQTKE"},
    {"name": "BACON SLICED", "category": "Food And Milks", "description": "Case", "price": 48.95, "square_token": "BGD6TJO4M6GJKSLBJ5FITW4P"},
    {"name": "BAGELS - BLUEBERRY - OLD TOWN BAKERY", "category": "Food And Milks", "description": "SIX PACK", "price": 3.68, "square_token": "GZ3WETF53L2VIDRO5MNJAEUO"},
    {"name": "BAGELS - CINNAMON RAISIN - OLD TOWN BAKING", "category": "Food And Milks", "description": "SIX PACK", "price": 3.68, "square_token": "IFGHZZX7HZJ7ETRNBN7CQADD"},
    {"name": "BAGELS - EVERYTHING - OLD TOWN BAKING", "category": "Food And Milks", "description": "SIX PACK", "price": 3.68, "square_token": "VLPGTSBGEJESKRWKU3KNEZJ3"},
    {"name": "BAGELS - JALAPENO CHEDDAR - OLD TOWN BAKING", "category": "Food And Milks", "description": "SIX PACK", "price": 3.68, "square_token": "VDTKPRZQ4VHNUHUDLU756Q4P"},
    {"name": "BAGELS - PLAIN - OLD TOWN BAKERY", "category": "Food And Milks", "description": "SIX PACK", "price": 3.68, "square_token": "DUYDYBJ633JO2AAUXMF6YMLC"},
    {"name": "BAKING POWDER (BAKERY)", "category": "Bakery Only", "description": "1 BOX", "price": 39.1, "square_token": "D552HEH5AGZN7C7XDTSAZCNH"},
    {"name": "BANANA BREAD", "category": "Food And Milks", "description": "Loaf", "price": 18.0, "square_token": "24UTVRR7GRI3ORNPI6VD6TMB"},
    {"name": "BASIL PESTO SPREAD (3/2 lb containers)", "category": "Food And Milks", "description": "6 CT.", "price": 55.18, "square_token": "4UB4J23TCP7SA5ZYLECZE3UT"},
    {"name": "BLACKBERRIES FROZEN", "category": "Bakery Only", "description": "1 Bag", "price": 5.0, "square_token": "Y5VA3V4TOQAWQ2FLDK66ZVRX"},
    {"name": "BLUEBERRY EXTRACT (BAKERY)", "category": "Bakery Only", "description": "1 BOTTLE", "price": 30.57, "square_token": "XBVNKLRZONAZY6XWXXZ27B7I"},
    {"name": "BLUEBERRY MUFFINS", "category": "Food And Milks", "description": "Dozen", "price": 11.0, "square_token": "LY7P5BRFKPBMZSK6S4KTM63W"},
    {"name": "BROWN SUGAR (BAKERY)", "category": "Bakery Only", "description": "12 - 2 LBS", "price": 30.57, "square_token": "NBDULLVLTJQALIUWEECWNJKB"},
    {"name": "BUTTER EXTRACT (BAKERY)", "category": "Bakery Only", "description": "1 BOTTLE", "price": 5.0, "square_token": "Z4VCAVBGOCMOKAVZLLEFRLIY"},
    {"name": "BUTTER", "category": "Food And Milks", "description": "Box of  PACKETS", "price": 40.77, "square_token": "JG6RTFE53TGDXUDDPKPJXLZ7"},
    {"name": "BUTTERMILK (BAKERY)", "category": "Bakery Only", "description": "5LBS BAG", "price": 30.57, "square_token": "ZKGE4DIDCDFE3RETJH57G42T"},
    {"name": "Bananas", "category": "Bakery Only", "description": "40 pounds green tip case", "price": 60.0, "square_token": "LI5BHXPIXCCPGXWQA2UE3N4I"},
    {"name": "Bananas", "category": "Food And Milks", "description": "10 pounds green tip", "price": 18.39, "square_token": "4KTSBAQ6BD4PIPBQHCFP64VU"},
    {"name": "Bar Keepers Friend", "category": "Cleaning Supplies", "description": "Bottle", "price": 6.78, "square_token": "PXHHBNMBOGFVHRNP2CF4X32E"},
    {"name": "Black Markers", "category": "Disposables", "description": "Box of 12", "price": 2.25, "square_token": "YCHZZV34PP73G7LZ624PIHHY"},
    {"name": "Black Markers (BAKERY)", "category": "Bakery Only", "description": "Box of 12", "price": 2.25, "square_token": "42YV2ZN45ZBQIBRXRD6H7HMG"},
    {"name": "Bunn 20138.1000 COFFEE FILTERS 1.5 GAL (RANCHERO LOCATION)", "category": "Coffee And Teas", "description": "500 per Case", "price": 20.12, "square_token": "3LHKLI4HTA5NRUA7XJSXANNM"},
    {"name": "Bunn 20157.0001 12 1/2\" x 4 3/4\" Gourmet Coffee Filter - 1000/Case", "category": "Coffee And Teas", "description": "500 per Case", "price": 28.2, "square_token": "GRFNDWMT6GA5OORCPK342SGH"},
    {"name": "Butter-Margarine (Bakery)", "category": "Bakery Only", "description": "30 - 1 lb.", "price": 120.0, "square_token": "5FPU2OZ5452QF4VATRUIY4F6"},
    {"name": "CAFEZA ESPRESSO CLEANER", "category": "Cleaning Supplies", "description": "Bottle", "price": 11.49, "square_token": "I23YSUTTKWMQIQ2R3ZPJW2D4"},
    {"name": "CANOLA OIL SPRAY (BAKERY)", "category": "Bakery Only", "description": "1 CAN", "price": 39.1, "square_token": "T3NPFPE3WJKECLWDWA7IPCY3"},
    {"name": "CAPORA - CARAMEL (Box of 6)", "category": "Syrups And Sauces", "description": "Box of 6", "price": 97.74, "square_token": "UWQTS5CAHDX4BIHXET4PDSXW"},
    {"name": "CAPORA - PUMPKIN SAUCE (Box of 6)", "category": "Syrups And Sauces", "description": "Box of 6", "price": 97.16, "square_token": "COMMY73T2X2JB36SHDR7JJVP"},
    {"name": "CAPORA - WHITE CHOCOLATE SAUCE (Box of 6)", "category": "Syrups And Sauces", "description": "Box of 6", "price": 92.0, "square_token": "XTQ37ZORARU4QXEXELFB4PUI"},
    {"name": "CARAMEL EXTRACT (1 GAL)", "category": "Bakery Only", "description": "1 GAL. Bottle", "price": 13.0, "square_token": "HIJ2QSLZCDRF5ISWPMACAM7J"},
    {"name": "CHAMOMILE TEA (6 Boxes)", "category": "Coffee And Teas", "description": "2 Boxes - 100 Tea Bags", "price": 58.07, "square_token": "VQWUC6K6257TMOD2J6GS2F7A"},
    {"name": "CHEDDAR CHEESE SLICED", "category": "Food And Milks", "description": "6  1.5LB. CASE", "price": 59.89, "square_token": "42DOFEIX5ZFHT6SNLRDSVJBX"},
    {"name": "CHOCOLATE CHIP MUFFINS", "category": "Food And Milks", "description": "Dozen", "price": 11.0, "square_token": "2UYLKTCIJNBDHGEBWRHH4S6G"},
    {"name": "CHOCOLATE CHIPS (BAKERY)", "category": "Bakery Only", "description": "25 LB BAG", "price": 137.53, "square_token": "KZWVNJ7KCFEAH7CIW7FBKXQV"},
    {"name": "CHOCOLATE CHIPS", "category": "Frappe Powders", "description": "4.5 LB BAG", "price": 13.35, "square_token": "VJ4QQBI5HYX4D25LCIF6MSAK"},
    {"name": "CHOCOLATE PUDDING (BAKERY)", "category": "Bakery Only", "description": "1 BOX", "price": 30.57, "square_token": "MVRR7JGUUW4GV7JNDPYOBTLD"},
    {"name": "CHOCOLATE THUNDER", "category": "Frappe Powders", "description": "20lb Bag", "price": 89.88, "square_token": "M62OFOJB26POW23HWANEOJUB"},
    {"name": "CINNAMON (BAKERY)", "category": "Bakery Only", "description": "1 BOX", "price": 30.57, "square_token": "H47NNO7KUQKEG7QTQ5NK2LOT"},
    {"name": "CINNAMON BREAD", "category": "Food And Milks", "description": "Loaf", "price": 18.0, "square_token": "IN3Q676SQPSBB4QULWJ6IE34"},
    {"name": "CINNAMON BUN Frappe", "category": "Frappe Powders", "description": "20lb Bag", "price": 87.01, "square_token": "KKIZ4YMLFOR6U4GUHOEYHOQA"},
    {"name": "CINNAMON ROLLS (24 SINGLES)", "category": "Food And Milks", "description": "24 SINGLES", "price": 25.2, "square_token": "CW72SBB75KHOMHTRY27G7CE5"},
    {"name": "CINNAMON SPRINKLES", "category": "Sweeteners and Extracts", "description": "16oz. Bottle", "price": 6.09, "square_token": "5Q2WFQ2TTZ35SJPX2MPGJD4G"},
    {"name": "COCONUT EXTACT (BAKERY)", "category": "Bakery Only", "description": "1 BOTTLE", "price": 30.57, "square_token": "UL3LAUIW7D5X4EXQ6XQUV2XF"},
    {"name": "COCONUT MILK", "category": "Food And Milks", "description": "Case of 12", "price": 49.27, "square_token": "DGQTRTQRUUELFDMJLGOUIUZN"},
    {"name": "COLD 16 OZ CUPS", "category": "Cups And Lids", "description": "Case of 1000", "price": 77.05, "square_token": "ICSZNBIQAHLQHNUFYCYOVLB7"},
    {"name": "COLD 24 OZ CUPS", "category": "Cups And Lids", "description": "Case of 600", "price": 73.6, "square_token": "GXXJ2LQAWRANF4N3YZSD76TX"},
    {"name": "COLD 32 OZ CUPS", "category": "Cups And Lids", "description": "Case of 300", "price": 49.45, "square_token": "GZI7M3VTTI5XNHYQ6UYTILRR"},
    {"name": "COLD BREW FILTER", "category": "Coffee And Teas", "description": "Pack 50", "price": 75.6, "square_token": "HVV6M7TXR7CQKANIEVNFB5Y7"},
    {"name": "COLD DOME LIDS M/L - C-KDL626", "category": "Cups And Lids", "description": "1 Case", "price": 35.2, "square_token": "EEUUSJ5HR5BBVCZSO44MIAL7"},
    {"name": "COLD DOME LIDS XL - Lollicup", "category": "Cups And Lids", "description": "Case of 600", "price": 61.24, "square_token": "ZOISR655LGDGVL3RWBYUK4RL"},
    {"name": "COLD FLAT LIDS M/L - C-KC626TS-SH", "category": "Cups And Lids", "description": "1Case", "price": 35.2, "square_token": "3H2GFG3AV45I2QAOVETWNG3X"},
    {"name": "COLD FLAT LIDS XL - Lollicup", "category": "Cups And Lids", "description": "Case of 600", "price": 90.56, "square_token": "Q3YPAKPKQ5AIIOGUQELOAQWI"},
    {"name": "COOKIE CRUMBLES", "category": "Sweeteners and Extracts", "description": "30 LBS.", "price": 103.48, "square_token": "PDNCAMVUMYWB6FFWEYXQSQS4"},
    {"name": "CRANBERRIES (BAKERY)", "category": "Bakery Only", "description": "1 BAG", "price": 30.57, "square_token": "R6NUZKOCHFVLZROF7VONYHMP"},
    {"name": "CREAM CHEESE (BAKERY )", "category": "Bakery Only", "description": "10- 3LB BLOCKS", "price": 94.88, "square_token": "GWBOB66DN6IOBFBUEYYR3S5W"},
    {"name": "CREAM CHEESE", "category": "Food And Milks", "description": "10- 3LB BLOCKS", "price": 109.25, "square_token": "AHQMSOARJNER747QV6MLH3VC"},
    {"name": "CRUSHED CANDY CANE TOPPING", "category": "Coffee And Teas", "description": "1 LB. Bag", "price": 5.75, "square_token": "N63UHPCCVSI3QRUUKC2GFVBS"},
    {"name": "CUP CARRIERS", "category": "Disposables", "description": "Case of 300", "price": 34.5, "square_token": "TTUY23CXENPDEONVFNQIAUIT"},
    {"name": "CUP SLEEVES", "category": "Cups And Lids", "description": "Case of 1000", "price": 30.5, "square_token": "OBPOFTMXRZGNKA46NSRQWSJW"},
    {"name": "Cake Pop (12 pack Seasonal Flavor)", "category": "Food And Milks", "description": "12 pops", "price": 21.0, "square_token": "BUNOQV4LGNCATPOWZBZ6BR5G"},
    {"name": "Capora Sauce Pump", "category": "Syrups And Sauces", "description": ".5 oz pump for sauces", "price": 6.25, "square_token": "BUSDVAD5HFKGDGTOVQQGM2PL"},
    {"name": "Cash Bags", "category": "Disposables", "description": "1000 Bags", "price": 72.6, "square_token": "AY2UW6ZGEI647Z2S6T4W3KLE"},
    {"name": "Cholula Hot Sauce", "category": "Food And Milks", "description": "Box of 200 - 7gr Packet", "price": 20.52, "square_token": "SHKQHSI7FTLF6N25YZC2BBYO"},
    {"name": "Citric Acid", "category": "Bakery Only", "description": "bag", "price": 30.0, "square_token": "L6FOKKBDRZPAZZIDXEA7B77S"},
    {"name": "Coarse Sea Salt", "category": "Sweeteners and Extracts", "description": "10 lbs.", "price": 13.79, "square_token": "24NGNJ3O4OMPY4BH6DDAWKQ4"},
    {"name": "DATE DOT STICKERS", "category": "Disposables", "description": "Pack", "price": 28.74, "square_token": "L2P52TQJXC2ITQAASSC63VZD"},
    {"name": "DAVINCI SYRUP - GINGERBREAD", "category": "Syrups And Sauces", "description": "Box of 4", "price": 32.76, "square_token": "26SB6JRJF57MMDAL52J3ULHO"},
    {"name": "DICED GREEN CHILES (BAKERY)", "category": "Bakery Only", "description": "1 CAN", "price": 39.1, "square_token": "5KY4GUFXIZQCTFKXV6JGB7YJ"},
    {"name": "DIMES", "category": "Coins And Cash", "description": "1 ROLL OF 40", "price": 4.0, "square_token": "SNR6V2XSCK42IVJB4YQ5CKGJ"},
    {"name": "DISH SOAP", "category": "Cleaning Supplies", "description": "Case of 4", "price": 39.99, "square_token": "XABIBXJYFN4GYQD46TCXSKVU"},
    {"name": "DISHWASHING GLOVES", "category": "Cleaning Supplies", "description": "12 pack", "price": 28.17, "square_token": "J52N4BPWRLLSYIJITP2HH6BQ"},
    {"name": "DOG TREATS", "category": "Food And Milks", "description": "Delivery from amazon. Box 10lb", "price": 18.98, "square_token": "4Z44VH7TGHD5G42NRK4T7BOC"},
    {"name": "DRIED BLUEBERRIES (BAKERY)", "category": "Bakery Only", "description": "1 BAG", "price": 10.0, "square_token": "PAQCBM7XOQLE6JTMWGJB5O7C"},
    {"name": "Dried Strawberries", "category": "Seasonal", "description": None, "price": 24.5, "square_token": "CYQ5FOLT2CAMPKRXUD3ODCHO"},
    {"name": "Drive Energy Mix BIB", "category": "Syrups And Sauces", "description": None, "price": 71.87, "square_token": "RREHXRVNKY7XXLWIMSYGCEU4"},
    {"name": "EARL GRAY TEA CASE", "category": "Coffee And Teas", "description": "168/case", "price": 38.51, "square_token": "SPAZT4AL4CTHBHYPOQFN55ZX"},
    {"name": "ENGLISH BREAKFAST TEA (6 Boxes)", "category": "Coffee And Teas", "description": "1 Box - 50 Tea Bags", "price": 58.07, "square_token": "GAJZPYBEHBYWUBUOFVKYCCPL"},
    {"name": "EQUAL PACKETS", "category": "Sweeteners and Extracts", "description": "2000 per Case", "price": 20.11, "square_token": "OUMW7HVU2J46C2RJNJO5EXP6"},
    {"name": "FAT FREE MILK", "category": "Food And Milks", "description": "1 GAL", "price": 4.71, "square_token": "2I2OPEKFMW6VRNF3LNS3O65M"},
    {"name": "FLAX SEED (BAKERY)", "category": "Bakery Only", "description": "1 BAG", "price": 30.57, "square_token": "Z5YJ5P46SSIQKHY4JM4OKRZM"},
    {"name": "FLOUR - 25 LB. BAG", "category": "Bakery Only", "description": "Bag", "price": 25.0, "square_token": "XZ353UQKGOYDANI5TCP7VLO2"},
    {"name": "FOOD COLORING Blue", "category": "Seasonal", "description": "16 oz. Bottle", "price": 7.99, "square_token": "O2VS3PPBZAPQXBI3XUEJWUT7"},
    {"name": "FOOD COLORING Green", "category": "Seasonal", "description": "16 oz. Bottle", "price": 7.99, "square_token": "LW3V3HJHYL4XDCECQ3UUFKP3"},
    {"name": "FOOD COLORING Red", "category": "Seasonal", "description": "16 oz. Bottle", "price": 7.99, "square_token": "LRJAZMVZS6ZSZKOS2GRTJFNW"},
    {"name": "FOOD CONTAINER (GREEN ROUND)", "category": "Bakery Only", "description": "500 PER CASE", "price": 63.81, "square_token": "VYHFQADUGNEG2YEPHZ7RV45A"},
    {"name": "FOOD CONTAINER LIDS (GREEN ROUND)", "category": "Bakery Only", "description": "500 PER CASE", "price": 63.81, "square_token": "U5C3G3CIJMVDULQOJSJQBAAC"},
    {"name": "FOOD HANDLER GLOVES", "category": "Disposables", "description": "Case of 1000", "price": 10.34, "square_token": "USLQTSH67LAFYK2ISSMLE7IE"},
    {"name": "FRAP BASE", "category": "Frappe Powders", "description": "20lb Bag", "price": 80.5, "square_token": "DVZNW2KCYNWBGFMDTRKEU3YI"},
    {"name": "Floor Cleaner", "category": "Cleaning Supplies", "description": "Case of 4", "price": 50.59, "square_token": "DCHAT34FNL34JTFCFAEBRFD7"},
    {"name": "Frappe Scoops", "category": "Frappe Powders", "description": "10 pack - 63cc", "price": 7.0, "square_token": "CHFQLKNHLPSB673MOMBLVTB5"},
    {"name": "Frozen Blueberries  (BAKERY)", "category": "Uncategorized", "description": "5LBS", "price": 20.57, "square_token": "ECLX2F2JIJQX6ZQPLCBVD36M"},
    {"name": "GIFT CARDS FULL SIZE", "category": "Disposables", "description": "100", "price": 0.0, "square_token": "FF5FU35QGFLQYRKYTHARDYR3"},
    {"name": "GOLDEN RAISINS (BAKERY)", "category": "Bakery Only", "description": "1 BOX", "price": 10.0, "square_token": "7CFBQP6XUXJLWXTHDRS3EYML"},
    {"name": "GREEN PAPER FOOD CONTAINER & LID (BAKERY)", "category": "Uncategorized", "description": "300 PER CASE", "price": 80.0, "square_token": "22BL5AKEBXRXA3I57H5CYZGI"},
    {"name": "GRINDZ GRINDER CLEANER", "category": "Cleaning Supplies", "description": "Bottle", "price": 25.87, "square_token": "4FNIC33R73OH2ALSQA2TWK4G"},
    {"name": "Grab n go - Nutella Go", "category": "Food And Milks", "description": "24 - 1.9 oz", "price": 58.94, "square_token": "7XX4ZFXQDTOPFFTGRAJBFTGQ"},
    {"name": "Guacamole", "category": "Food And Milks", "description": "12/1 LB pouches", "price": 75.69, "square_token": "BVNZLHSZSFUEDY2POOUQORHW"},
    {"name": "HALF & HALF", "category": "Food And Milks", "description": "12-1 QT", "price": 42.09, "square_token": "ICIBCUUNVNRYVKEIRDZM3OIN"},
    {"name": "HAND SOAP", "category": "Cleaning Supplies", "description": "Case of 4", "price": 19.54, "square_token": "P3CLT3IM5YMC5YEZFLH7NFPE"},
    {"name": "HAZELNUT EXTRACT (1 GAL)", "category": "Bakery Only", "description": "1 GAL. Bottle", "price": 13.0, "square_token": "AH3GQ3DYPL3CQASPRE3GE4KH"},
    {"name": "HEAVY CREAM", "category": "Food And Milks", "description": "Case 6 half gallons", "price": 55.03, "square_token": "K4FNIWFK35RTFFXBNBXXQLX4"},
    {"name": "HINGED LID CONTAINER 6x6 -300", "category": "Disposables", "description": "300 PER CASE", "price": 30.19, "square_token": "UVKWKP5XXFVIN5HL3UBBKJUD"},
    {"name": "HONEY PACKETS", "category": "Food And Milks", "description": "200 - 9g PACKETS", "price": 36.05, "square_token": "2FTSCR7KO2JENA443D3P74ZN"},
    {"name": "HORCHATA MIX", "category": "Syrups And Sauces", "description": "BIB", "price": 73.37, "square_token": "NIFXK4YR3SFOZOVRKPX3FTPD"},
    {"name": "HOT 12 OZ CUPS", "category": "Cups And Lids", "description": "Case of 1000", "price": 69.86, "square_token": "H2J72SJUNE5AP3PI64XUD7Q6"},
    {"name": "HOT 16 OZ CUPS", "category": "Cups And Lids", "description": "Case of 1000", "price": 63.25, "square_token": "GDN7B66L63XP4HSN34MOLEZQ"},
    {"name": "HOT 20 OZ CUPS", "category": "Cups And Lids", "description": "Case", "price": 46.0, "square_token": "4CYXAI7SIBEW32C6V37MVMGA"},
    {"name": "HOT LIDS - C-KDL516B-PP", "category": "Cups And Lids", "description": "Case of 1000", "price": 39.1, "square_token": "PWYRPWO6TFY4OAEMSBD27JBC"},
    {"name": "ICED TEA BLACK", "category": "Coffee And Teas", "description": "(48) 1oz. Bags", "price": 31.61, "square_token": "RT2EQKOHXNXDW3IDH5X7FUVT"},
    {"name": "ICED TEA GREEN", "category": "Coffee And Teas", "description": "(48) 1oz. Bags", "price": 36.21, "square_token": "FERZBN37JBIIDAFBJB3NRELF"},
    {"name": "ICED TEA PASSION FRUIT", "category": "Coffee And Teas", "description": "(48) 1oz. Bags", "price": 30.46, "square_token": "7GJ2USBI4RTRN7DT54HSRDV7"},
    {"name": "JAPANESE SENCHA TEA (6 Boxes)", "category": "Coffee And Teas", "description": None, "price": 58.07, "square_token": "TB77EKTLVUMPCALGFJY234BD"},
    {"name": "JUMBO GALLON BAGS", "category": "Bakery Only", "description": "1 Box", "price": 39.1, "square_token": "RQ3Z5PJF5NL5USEQ6NE4GXAO"},
    {"name": "KIDS CUPS", "category": "Cups And Lids", "description": "250 per Case", "price": 68.98, "square_token": "Y33N2LEZG4HGXSSYZDF2AYZG"},
    {"name": "KNIVES", "category": "Disposables", "description": "1000 per Case", "price": 27.59, "square_token": "LAISC2BBZJSBX2LWQUXI2BLC"},
    {"name": "Keto Egg Bites (30 egg cups)", "category": "Food And Milks", "description": None, "price": 28.0, "square_token": "JNFZG5FKG3EV6GUOASEIKDLA"},
    {"name": "Klatch 310gram Retail Bags", "category": "Coffee And Teas", "description": "Belle Espresso Roast", "price": 12.36, "square_token": "XRBKQE6H424WOSZV2RVE5JGM"},
    {"name": "Klatch Coffee Belle Espresso 5 lb Bag", "category": "Coffee And Teas", "description": "Min. Order of 40 Bags\nBelle Espresso Roast", "price": 67.04, "square_token": "CSDR6KLEMZLYWYHMGFXK4ZXM"},
    {"name": "Klatch Coffee DECAF 5 lb Bag", "category": "Coffee And Teas", "description": "Decaf Roast", "price": 60.28, "square_token": "SBYOC5GJS62A5R7KGCYD4OSP"},
    {"name": "Klatch Dark Roast Blend (5 lb. bag)", "category": "Coffee And Teas", "description": "Dark Roast for Frappe Toddy", "price": 54.14, "square_token": "VZZJUVESGCDZO6IOESN554HD"},
    {"name": "LABEL MAKER TAPE", "category": "Disposables", "description": "1 Roll", "price": 4.8, "square_token": "PT4MABRSNN6IE3YO4SFZMF24"},
    {"name": "LARGE SHELLED EGGS", "category": "Food And Milks", "description": "15 Dozen", "price": 36.5, "square_token": "A7UYJX4EIF2VMYNVU47T64SE"},
    {"name": "LARGE TRASH BAGS 33 gal.", "category": "Cleaning Supplies", "description": "250 per Case", "price": 28.73, "square_token": "PPTG3YQWIKOKOXMB6VPTFGU6"},
    {"name": "LEMON JUICE (BAKERY)", "category": "Bakery Only", "description": "1 BOTTLE", "price": 3.0, "square_token": "XNKQ6G3QAC6EKUCAV63SXQKJ"},
    {"name": "LEMONADE CONCENTRATE BiB", "category": "Seasonal", "description": "5 gal. BIB", "price": 67.27, "square_token": "FEOMLPDSO2N4NAC6CDGYXJQT"},
    {"name": "LEMONADE Jugs", "category": "Syrups And Sauces", "description": "4 Gallons", "price": 38.88, "square_token": "HD3CQ7S4DRMOZO6ZPJ3ZSBP2"},
    {"name": "Lavender Blackberry Scones (8)", "category": "Food And Milks", "description": "8 Scones", "price": 14.0, "square_token": "RAC2WGXHJ7DA5ECXOL4JC3W7"},
    {"name": "Lettuce Iceberg", "category": "Food And Milks", "description": "6 heads", "price": 22.48, "square_token": "EN3RXXFFTKYY2TQ72SROAB3W"},
    {"name": "MATCHA FRAPPE POWDER", "category": "Frappe Powders", "description": "20lb Bag", "price": 89.63, "square_token": "NPJ3DVFHMUHGNVJ6OOTNQVVB"},
    {"name": "MEDIUM SHELLED EGGS", "category": "Bakery Only", "description": "15 Dozen", "price": 40.0, "square_token": "BPIBGK5Z572ANV4UN6MK7W2F"},
    {"name": "MILK 2% -1 GALLON (BAKERY)", "category": "Uncategorized", "description": "1 GAL", "price": 4.0, "square_token": "P63M5AYPIKROCZND34FC6A7O"},
    {"name": "MINT EXTRACT", "category": "Bakery Only", "description": "1 BOTTLE", "price": 4.0, "square_token": "K25E3UFB5XHSFSHLDKHKCHBQ"},
    {"name": "MOP HEAD", "category": "Cleaning Supplies", "description": "1each", "price": 5.18, "square_token": "3SZJYTOU2QPXPETMG6PCRECP"},
    {"name": "MOZZARELLA SHREDDED", "category": "Food And Milks", "description": "20lb Bag", "price": 61.87, "square_token": "E63GFS6MLFRT6AO5PT72IKQY"},
    {"name": "MUFFIN LINERS", "category": "Bakery Only", "description": "1 CASE", "price": 25.0, "square_token": "CV4L46VQVJAZYWQ6LQZO3DYD"},
    {"name": "Mayonnaise - 1 gal.", "category": "Food And Milks", "description": "1 Gallon", "price": 16.61, "square_token": "UG3EFBWKIPUV2C5ALX5GUZ6G"},
    {"name": "Metro Deli, BBQ Chips", "category": "Food And Milks", "description": "60 - 1.38 oz", "price": 47.22, "square_token": "SVZB2CEKKI4GYNF64GLMYI6W"},
    {"name": "Metro Deli, Jalapeno Cheese Chips", "category": "Food And Milks", "description": "60 - 1.38 oz", "price": 39.89, "square_token": "3J2UMNYWEMW3HAGTT7BN6DDV"},
    {"name": "Metro Deli, Tropical Snack Mix", "category": "Food And Milks", "description": "30-2oz", "price": 26.16, "square_token": "5JXSBDEZDCDIO762HB56QZGW"},
    {"name": "Metro Deli,Dill Pickle Snack Mix", "category": "Food And Milks", "description": "30-2oz", "price": 29.53, "square_token": "TPAL74FPJKJYMYGCNHUDHU6G"},
    {"name": "Microfiber Rags (200 Pack)", "category": "Cleaning Supplies", "description": "200 pack", "price": 36.65, "square_token": "NXGP2HYMKPR4CKZYO6ROWFVT"},
    {"name": "Mint NO Chip", "category": "Frappe Powders", "description": "20lb Bag", "price": 91.88, "square_token": "PZPYDZ5FYPG4U4CRHB7AYNIZ"},
    {"name": "NAPKINS - 1 ply", "category": "Disposables", "description": "Case of 3000", "price": 18.97, "square_token": "Q6XLUDJS47I5KE42324ABEOZ"},
    {"name": "NICKELS", "category": "Coins And Cash", "description": "1 ROLL OF 40", "price": 2.0, "square_token": "RGHZ4I5LDHMYBMGDDHR2BSGX"},
    {"name": "NON-DAIRY CREAMER (1- 35.3 oz Container)", "category": "Frappe Powders", "description": "1 - 35.3 oz Container", "price": 5.78, "square_token": "GZBTH2BFPNWQUA4PFOLORWIK"},
    {"name": "Noble Sea Breeze Bathroom Scent", "category": "Cleaning Supplies", "description": "7.25 oz. Bottle", "price": 3.78, "square_token": "2QSYCK6OUJ3XRHVBPAGLHTHZ"},
    {"name": "Nutella", "category": "Food And Milks", "description": "Case", "price": 70.59, "square_token": "KCKSWOVRU4Y4S2MKIWJWXARU"},
    {"name": "OAT MILK", "category": "Food And Milks", "description": "Case of 12", "price": 42.17, "square_token": "UR5R5A2742W2UPBZBZ2RQNFV"},
    {"name": "OATMEAL", "category": "Food And Milks", "description": "Pack 24", "price": 24.0, "square_token": "HCXR4CKE2WSXSKLDGGXV5WAY"},
    {"name": "OIL - 1 GALLON", "category": "Bakery Only", "description": "1 GAL. BOTTLE", "price": 25.0, "square_token": "FBAWBSRUQ4UC4UIG5LLL75O3"},
    {"name": "ORANGE EXTRACT (BAKERY)", "category": "Uncategorized", "description": "1 Bottle", "price": 13.0, "square_token": "JNQT33W3SFNJ3OS6QDMPOB2G"},
    {"name": "ORANGE JUICE (BAKERY)", "category": "Bakery Only", "description": "1 BOTTLE", "price": 30.57, "square_token": "DC3FC4FKUBVIJSAGH2STD2AE"},
    {"name": "OREGON CHAI (Case OF 12)", "category": "Food And Milks", "description": "Case OF 12", "price": 59.78, "square_token": "VFKQIFY4RSLO25UP66V6NN5N"},
    {"name": "ORGANIC GREEN CITRON TEA (6 Boxes)", "category": "Coffee And Teas", "description": None, "price": 58.07, "square_token": "TLQWF4H4GUUSDFJRJ7C5DHA6"},
    {"name": "ORGANIC PEPPERMINT TEA (6 boxes)", "category": "Coffee And Teas", "description": None, "price": 58.07, "square_token": "W3AX4QCXHJ2DFIGAV5GN4LAD"},
    {"name": "OVEN CLEANER (BAKERY)", "category": "Bakery Only", "description": "1 CAN", "price": 30.57, "square_token": "LVS5KVTAOKLIOZ2Y5YJXEJRN"},
    {"name": "Orange Juice", "category": "Food And Milks", "description": "24 - 10 oz.", "price": 43.51, "square_token": "SZZLACQFMGZJT24XKCUP36J3"},
    {"name": "PAPER NOTEBOOK", "category": "Disposables", "description": "Per Notebook", "price": 1.6, "square_token": "CZVMC3SZTC263BHD3BTIIQAU"},
    {"name": "PAPER TOWELS", "category": "Cleaning Supplies", "description": "Case of 6", "price": 28.74, "square_token": "VOSOEDX3Y5BZXDYRSETYLM2N"},
    {"name": "PARCHMENT SHEETS", "category": "Disposables", "description": "CASE OF 1000 SHEETS", "price": 40.24, "square_token": "BBMAEFGFC3WMHUFRWFRJDI3K"},
    {"name": "PARIS TEA (6 Boxes)", "category": "Coffee And Teas", "description": None, "price": 58.07, "square_token": "BN3AAW3KXWEJZJHHZKYBCTFX"},
    {"name": "PEACH EXTRACT (BAKERY)", "category": "Bakery Only", "description": "1 Bottle", "price": 13.0, "square_token": "GSZSTUCWBMS5X5DINL2DDVMM"},
    {"name": "PEANUTS", "category": "Frappe Powders", "description": "30lb Bag", "price": 66.69, "square_token": "R7N4Z3MO7KTXHT62SGKKFF73"},
    {"name": "PENNIES", "category": "Coins And Cash", "description": "1 ROLL OF 50", "price": 0.5, "square_token": "AV7GW72CBBTVEEW4XKSOCEVU"},
    {"name": "PENS", "category": "Disposables", "description": "Box", "price": 42.7, "square_token": "XQFBSJSLSNBSL7SOEBYFTZXH"},
    {"name": "PEPPER JACK CHEESE SLICED", "category": "Food And Milks", "description": "6  1.5LB. CASE", "price": 57.91, "square_token": "NW6OEOIOPU35HPO2C7QQB42X"},
    {"name": "PEPPERONI", "category": "Food And Milks", "description": "10 lb. BOX", "price": 58.57, "square_token": "G5C5WEPLMUIS4USMOFJJNEOY"},
    {"name": "PIZZA SAUCE", "category": "Food And Milks", "description": "6 #10 CANS", "price": 50.5, "square_token": "REKHMRGM6DCD743FWIY6OO7W"},
    {"name": "PLASTIC FORKS", "category": "Disposables", "description": "1000 per Case", "price": 25.28, "square_token": "ZHVTYBMFCECV5WUV3IDAVBUO"},
    {"name": "POPPY SEED  (BAKERY)", "category": "Uncategorized", "description": "1 BAG", "price": 30.0, "square_token": "TTC3LH3BAK7Q7MSCDDJBUSHA"},
    {"name": "POWDERED SUGAR (BAKERY)", "category": "Bakery Only", "description": "25 LBS bag", "price": 30.57, "square_token": "I6GZTL7PNJD5B6K55JNNMREY"},
    {"name": "PROVOLONE CHEESE SLICED", "category": "Food And Milks", "description": "6  1.5LB. CASE", "price": 55.84, "square_token": "PESZFMLVTLW7RK4OA4RJD6C3"},
    {"name": "PUMPKIN (BAKERY)", "category": "Bakery Only", "description": "1 CAN", "price": 30.57, "square_token": "XBS3ZP2C43TWBW44NGBQ455F"},
    {"name": "PUMPKIN BREAD", "category": "Food And Milks", "description": "Loaf", "price": 18.0, "square_token": "Y2YYHXOQ4LOCW7GDRN7VD4OK"},
    {"name": "Paper Handled Bags", "category": "Disposables", "description": "Box of 250 for food carry out\n10X6.75X12", "price": 57.03, "square_token": "GX4BSX7MFQKY6THIUHGNDI7Z"},
    {"name": "Pastry BAGS", "category": "Disposables", "description": "Box of 2000", "price": 53.8, "square_token": "2J5JUEWC4PXA3CP36FJBY2UI"},
    {"name": "Peanut Butter", "category": "Food And Milks", "description": "case of 6", "price": 83.57, "square_token": "QE73BSUBSAWUC7S2ZGLCW37L"},
    {"name": "Pumpkin pie spice topping", "category": "Sweeteners and Extracts", "description": "16oz. Bottle", "price": 11.15, "square_token": "7F33JBEO4WO2K7Y4FRIQPC66"},
    {"name": "QUARTERS", "category": "Coins And Cash", "description": "1 ROLL", "price": 10.0, "square_token": "EW2GPTZA6JX3UOS7THCODQDK"},
    {"name": "RASPBERRY TEA (6 boxes)", "category": "Coffee And Teas", "description": None, "price": 58.07, "square_token": "656EFOF4BGK2IETL5Q3D4Q3I"},
    {"name": "RAW SUGAR 2lb", "category": "Sweeteners and Extracts", "description": "2lb Box", "price": 5.25, "square_token": "XRU4JKSDUM4IJOI2DLAEARJZ"},
    {"name": "RAW SUGAR PACKETS", "category": "Sweeteners and Extracts", "description": "1200 per Case", "price": 35.07, "square_token": "3FGTGXRW42LGHLWAWUTRH4JX"},
    {"name": "ROLLED OATS (BAKERY)", "category": "Bakery Only", "description": "1 BAG", "price": 30.57, "square_token": "HWJ6LUR7MZ3ERAOI7LZ5TXAK"},
    {"name": "SALT 25 LB. BAG", "category": "Bakery Only", "description": "Bag", "price": 13.0, "square_token": "H6HJ5MLYMD6XWQLXQQECFFRL"},
    {"name": "SAMPLE CUPS CASE", "category": "Disposables", "description": "2500", "price": 23.56, "square_token": "D67YZU67IYZSP5Y26FFNIVO7"},
    {"name": "SANITIZER", "category": "Cleaning Supplies", "description": "Case of 4", "price": 95.44, "square_token": "7G7UCWL3BHADPPUFH5XZEY3V"},
    {"name": "SAUSAGE", "category": "Food And Milks", "description": "10 lb. BOX", "price": 53.61, "square_token": "NYQOUMAULIY2KQQOHUOEIJVN"},
    {"name": "SCRAMBLED EGG PATTIES", "category": "Food And Milks", "description": "Case 120 CT", "price": 53.68, "square_token": "ZMLA76O3RPZVI4ICPOK7NDCB"},
    {"name": "SCRUB BRUSH", "category": "Cleaning Supplies", "description": "1 Ea.", "price": 6.2, "square_token": "RUPVX66QUICTRWDAXHMS6A5V"},
    {"name": "SEA SALT (BAKERY)", "category": "Bakery Only", "description": "1", "price": 30.57, "square_token": "A2PE7C45HDOZR5B2WIJPUDRD"},
    {"name": "SHREDDED CHEESE (BAKERY)", "category": "Bakery Only", "description": "5LBS", "price": 30.57, "square_token": "MTAIQPSMFLDDMSVJ54O6X3EU"},
    {"name": "SIX BEANS -  SUGAR FREE COCONUT SYRUP (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 5.5 BOTTLES", "price": 11.5, "square_token": "BXB47VDVHR4HNXQ2KCEDEINI"},
    {"name": "SIX BEANS - CARAMEL SYRUP", "category": "Syrups And Sauces", "description": "20 LB. BAG", "price": 85.52, "square_token": "VIRXNBMCDE7LNXLG4Y5N4NC7"},
    {"name": "SIX BEANS - Coconut Syrup", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 15.5, "square_token": "FSC36PWOORFG6C2WN2T2KNJ5"},
    {"name": "SIX BEANS - HAZELNUT SYRUP (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 4 BOTTLES", "price": 14.5, "square_token": "PT6IM7IMGZSXGHHIH3ONUBID"},
    {"name": "SIX BEANS - LUCKY LEPRECHAUN (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 2 BOTTLES", "price": 8.0, "square_token": "426LLFJWKWDBGZPJTSG7YN6Z"},
    {"name": "SIX BEANS - SALTED CARAMEL SYRUP", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 15.5, "square_token": "54RDXKARRFABQ3QGZTGT4KAJ"},
    {"name": "SIX BEANS - SUGAR FREE CARAMEL SYRUP (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 5.5 BOTTLES", "price": 11.5, "square_token": "RGNZ32I25HHDM2GTUH3ZUH7F"},
    {"name": "SIX BEANS - SUGAR FREE HAZELNUT SYRUP (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 3 BOTTLES", "price": 11.5, "square_token": "4RVMJPJKEIW4ABFR3TUO3QML"},
    {"name": "SIX BEANS - SUGAR FREE SALTED CARAMEL SYRUP (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 5.5 BOTTLES", "price": 11.5, "square_token": "TRBCDRDA7E7SZQFT2MFGTGUP"},
    {"name": "SIX BEANS - SUGAR FREE STRAWBERRY SYRUP (1 BAG)", "category": "Syrups And Sauces", "description": "MAKES 5.5 BOTTLES", "price": 11.5, "square_token": "XS4WQ4GDPUPHVX6J4HAFBTRN"},
    {"name": "SIX BEANS CHOCOLATE SAUCE", "category": "Syrups And Sauces", "description": "20lb Bag", "price": 97.5, "square_token": "2BMHGLW3IBCG7OHQQTIP5WCQ"},
    {"name": "SIX BEANS SYRUP - BLUEBERRY", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 14.0, "square_token": "XUMEQEWTDAPUC3UUVTPGRVN2"},
    {"name": "SIX BEANS SYRUP - BROWN SUGAR", "category": "Syrups And Sauces", "description": "Make 4 Bottles", "price": 12.0, "square_token": "G5E6YTMTV3AVWG6DSU7FAJHI"},
    {"name": "SIX BEANS SYRUP - ORANGE", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 14.0, "square_token": "TOV6QJVDMOXQFRHK4KZ7U7CC"},
    {"name": "SIX BEANS SYRUP - PEACH", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 14.0, "square_token": "D6XMIJ5XZWBOWU7AYS3V627H"},
    {"name": "SIX BEANS SYRUP - PEPPERMINT", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 13.5, "square_token": "VKJQNRJD66COGC2M24R7YNYL"},
    {"name": "SIX BEANS SYRUP - SIMPLE", "category": "Syrups And Sauces", "description": "Make 4 Bottles", "price": 6.0, "square_token": "O645R4KKK3RGXVD4MZRCKQ7F"},
    {"name": "SIX BEANS SYRUP - STRAWBERRY", "category": "Syrups And Sauces", "description": "Makes 4 Bottles", "price": 14.0, "square_token": "XRVF7BVXU6IKQANIZMNKZZVW"},
    {"name": "SIX BEANS SYRUP - SUGAR FREE VANILLA", "category": "Syrups And Sauces", "description": "Makes 3 Bottles", "price": 11.5, "square_token": "FOSQB67D3H4YCLFUPPERNUNG"},
    {"name": "SIX BEANS SYRUP - VANILLA", "category": "Syrups And Sauces", "description": "20 lb. bag", "price": 66.21, "square_token": "T23ZT3U72B5GEZ3PX7JOVKRO"},
    {"name": "SMALL TRASH BAGS 10 gal.", "category": "Cleaning Supplies", "description": "1000 per Case", "price": 36.79, "square_token": "SYH2LJEG5ECIT3SFLSHTDHPM"},
    {"name": "SOS PADS (BAKERY)", "category": "Bakery Only", "description": "Case of 120", "price": 56.92, "square_token": "GLDVTJ3QNI2P3AE54D5EQK2P"},
    {"name": "SOS PADS", "category": "Cleaning Supplies", "description": "Case of 120", "price": 56.92, "square_token": "4OANPQLH6HZTUR3SHYNS64K2"},
    {"name": "SOUR CREAM (BAKERY)", "category": "Bakery Only", "description": "CASE OF 6 - 1 GAL", "price": 30.57, "square_token": "WWGNOEEJ6QQJRHMSMXJTCWSO"},
    {"name": "SOY MILK", "category": "Food And Milks", "description": "Case OF 12", "price": 46.63, "square_token": "QWFGKRZCX4KAVUXXDMGLY4EI"},
    {"name": "SPLENDA - BIG BAG", "category": "Bakery Only", "description": "Bag", "price": 5.0, "square_token": "K6T3P57DRLA64PDBJ6X25GZN"},
    {"name": "SPLENDA PACKETS", "category": "Sweeteners and Extracts", "description": "2000 per Case", "price": 22.99, "square_token": "UIU2PKANTU6FXMECBLFZASHI"},
    {"name": "SPONGES", "category": "Cleaning Supplies", "description": "Pack of 6", "price": 2.99, "square_token": "BA3VWWIQL3HH7APWZRQY2DA6"},
    {"name": "SPOONS", "category": "Disposables", "description": "1000 per Case", "price": 30.46, "square_token": "KZF2EBPAIW63YMHUKPURK4N5"},
    {"name": "STEVIA PACKETS", "category": "Sweeteners and Extracts", "description": "1000 per Case", "price": 25.86, "square_token": "DBKDALKOSYWF6EE33NX6PET5"},
    {"name": "STRAWBERRY EXTRACT (BAKERY)", "category": "Uncategorized", "description": "1 Bottle", "price": 13.0, "square_token": "TN6RPE4DOKQQFYVISDQSMB5G"},
    {"name": "STRAWS (ALL COLORS)- C9075 Lollicup", "category": "Cups And Lids", "description": "Case of 2500", "price": 29.33, "square_token": "SQFDVCFG6URIBRQVO7CALF7G"},
    {"name": "SUGAR FREE CARAMEL SAUCE", "category": "Syrups And Sauces", "description": "Box of 4", "price": 103.49, "square_token": "3EQ4LBZXFCYLEGC3OJEKFXSS"},
    {"name": "SUGAR FREE CHOCOLATE SAUCE", "category": "Syrups And Sauces", "description": "Box of 4", "price": 90.27, "square_token": "SXGO5AAZK6DQ5AYCI3T6VH6F"},
    {"name": "SUGAR FREE FRAP BASE", "category": "Frappe Powders", "description": "12lb Bag", "price": 84.0, "square_token": "C776VHVVKCHQQEZKDA7J4L2C"},
    {"name": "SUGAR FREE TORANI SYRUP - ORANGE", "category": "Syrups And Sauces", "description": "Box of 12", "price": 95.43, "square_token": "75IDTDV7RIL2ZWRYLCI2FO52"},
    {"name": "SUGAR FREE TORANI SYRUP - PEACH", "category": "Syrups And Sauces", "description": "Box of 12", "price": 95.43, "square_token": "YQIRKM5SG2WYSELJ3IVDOH42"},
    {"name": "SUGAR FREE TORANI SYRUP - RASPBERRY", "category": "Syrups And Sauces", "description": "Box of 12", "price": 95.44, "square_token": "SHVQOTLWU43KITG5JVWM4QQB"},
    {"name": "SUGAR FREE TORANI SYRUP -HAZELNUT", "category": "Syrups And Sauces", "description": "Box of 12", "price": 85.21, "square_token": "MUTDVV5CUIURXI4RC4MTSNW7"},
    {"name": "SUGAR FREE WHITE CHOCOLATE SAUCE", "category": "Syrups And Sauces", "description": "Box of 4", "price": 103.49, "square_token": "UBRN27CNK6TQYR4T3W6SZFMX"},
    {"name": "SWEET & LOW PACKETS", "category": "Sweeteners and Extracts", "description": "2000 per Case", "price": 12.63, "square_token": "GE635UARHCXJEDXR5PD63NV7"},
    {"name": "SWEETENED CONDENSED MILK", "category": "Syrups And Sauces", "description": "1 Case (24-14oz Cans)", "price": 97.65, "square_token": "LJNWOTCR2RC2TR7LRHA4Y3MJ"},
    {"name": "SYRUP BAGS (BAKERY)", "category": "Uncategorized", "description": "1 BOX", "price": 25.0, "square_token": "TGBQQE4CRRVJJDUBKVEY2ZUD"},
    {"name": "Scissors (1)", "category": "Disposables", "description": "1", "price": 2.5, "square_token": "76TMJNYFA3O4GASTKJBELBLU"},
    {"name": "Sugar Cookies (12 pack Seasonal Flavor)", "category": "Food And Milks", "description": "12 pops", "price": 12.0, "square_token": "BQQBKJVBWE4UNL6DLB3FGXWV"},
    {"name": "Sugar Packets", "category": "Sweeteners and Extracts", "description": "2000 per Case", "price": 18.28, "square_token": "TCQUE5DPCOWWCZJ3RTIRQ3VG"},
    {"name": "T-shirt", "category": "Merchandise", "description": "1 apron", "price": 12.0, "square_token": "H44XBXNK53U75BDYIWHZY24A"},
    {"name": "TAPE", "category": "Disposables", "description": "Roll", "price": 2.1, "square_token": "E4C4QDMWNUTBE7F3SCJXWFVJ"},
    {"name": "TEA ZONE - GREEN APPLE Lollicup 5", "category": "Syrups And Sauces", "description": "Box of 6", "price": 74.18, "square_token": "C2WTST25BUQGJP46KWOH4J5X"},
    {"name": "TEA ZONE - MANGO Lollicup 6", "category": "Syrups And Sauces", "description": "Box of 6", "price": 70.72, "square_token": "TNAM2432AQ4DDIL3AL7AF5YM"},
    {"name": "TEA ZONE - PEACH Lollicup 4", "category": "Syrups And Sauces", "description": "Box of 6", "price": 70.72, "square_token": "JRNTB2GYGD3R6HLS3OJ7OTGX"},
    {"name": "TEA ZONE - POMEGRANATE Lollicup 4", "category": "Syrups And Sauces", "description": "Box of 6", "price": 70.72, "square_token": "GFLQ5OH6SUQIFRFJWIKWLZYY"},
    {"name": "TEA ZONE - RASPBERRY Lollicup 4", "category": "Syrups And Sauces", "description": "Box of 6", "price": 89.7, "square_token": "HKURG7DZ5DAEBOJPQVZWBQT7"},
    {"name": "TEA ZONE - STRAWBERRY Lollicup 9", "category": "Syrups And Sauces", "description": "Box of 6", "price": 70.72, "square_token": "WAVBZ76YXZTOA4OJZF7JNGLK"},
    {"name": "TOILET PAPER", "category": "Cleaning Supplies", "description": "96 Rolls", "price": 39.99, "square_token": "BZUIZ6J5RVB3D3IJJOAKFCYR"},
    {"name": "TOILET SEAT COVERS", "category": "Cleaning Supplies", "description": "5000 SEAT COVERS (20 PACKS)", "price": 37.95, "square_token": "JECYHEKTZB5V443MNCOUMMQP"},
    {"name": "TORANI SYRUP - BLACKBERRY", "category": "Syrups And Sauces", "description": "Box of 6", "price": 57.49, "square_token": "MJL7MCYVWBCXPGHU6356X3IC"},
    {"name": "TORANI SYRUP - BLUE RASPBERRY (Box of 12)", "category": "Syrups And Sauces", "description": "Box of 6", "price": 57.49, "square_token": "4QYC4SEE2TGKQJH4TD4J5VZ3"},
    {"name": "TORANI SYRUP - CHERRY", "category": "Syrups And Sauces", "description": "Box of 6", "price": 57.49, "square_token": "YHP2GAWRADXIZO5KUYADLC26"},
    {"name": "TORANI SYRUP - CINNAMON", "category": "Syrups And Sauces", "description": "Box of 6", "price": 57.49, "square_token": "IJWDYQPLY7XH5WIF3JJ2QGXB"},
    {"name": "TORANI SYRUP - Creme De Banana(Box of 6, 1 liter bottles)", "category": "Syrups And Sauces", "description": "Box of 12", "price": 57.5, "square_token": "MXHQAFK3RM2Y552EENGYQNIS"},
    {"name": "TORANI SYRUP - Irish Cream", "category": "Syrups And Sauces", "description": "Box of 4", "price": 30.46, "square_token": "JEO7Q67FNWSVNRLXVUFYBVER"},
    {"name": "TORANI SYRUP - Kiwi (Box of 4)", "category": "Syrups And Sauces", "description": "Box of 4", "price": 31.62, "square_token": "Z4NQVOGRWSZ6QCX5CLZQGOMQ"},
    {"name": "TORANI SYRUP - Lavender (Box of 12)", "category": "Syrups And Sauces", "description": "Box of 6", "price": 57.49, "square_token": "PQRNSYNIKLRK7MYTDVE4NB3Q"},
    {"name": "TORANI SYRUP - MACADAMIA NUT (Box of 12)", "category": "Syrups And Sauces", "description": "Box of 12", "price": 95.44, "square_token": "35CHPG6X6T4IUYNW5MD6VBM5"},
    {"name": "TORANI SYRUP - Pineapple (Box of 4)", "category": "Syrups And Sauces", "description": "Box of 4", "price": 31.62, "square_token": "CGXH3NLIZ2FPCXCDRUUFXBM4"},
    {"name": "TORANI SYRUP - Pineapple (Case of 4)", "category": "Syrups And Sauces", "description": "Box of 12", "price": 36.62, "square_token": "WK5VHEHGCH7HW3KLNQ4AWKDX"},
    {"name": "TORANI SYRUP - RASPBERRY", "category": "Syrups And Sauces", "description": "Box of 6", "price": 57.49, "square_token": "27TFO5Q2PUA4IRWMMH5PY3E3"},
    {"name": "TORANI SYRUP - TOASTED MARSHMALLOW", "category": "Syrups And Sauces", "description": "Box of 12", "price": 81.29, "square_token": "T2H32XY57IYE3QIWT2AEL22U"},
    {"name": "TURKEY BREAST SLICED", "category": "Food And Milks", "description": "6  2LB. CASE", "price": 72.75, "square_token": "NEN7KUEOX4EKGUA5DBWDLT47"},
    {"name": "Tomatoes whole", "category": "Food And Milks", "description": "25 lbs. #1", "price": 67.62, "square_token": "P3GBKLUIBEKKLBZT6BFYYXPD"},
    {"name": "UBE POWDER", "category": "Seasonal", "description": "1", "price": 25.3, "square_token": "D4SX4FOGCM7EPSRKOW7BRLD5"},
    {"name": "Urnex Tabs COFFEE POT CLEANER", "category": "Cleaning Supplies", "description": "Bottle", "price": 10.33, "square_token": "ALYA7P5MUO6I7GH2L2KJFC3B"},
    {"name": "VANILLA EXTRACT (1 GAL)", "category": "Bakery Only", "description": "1 GAL. Bottle", "price": 13.0, "square_token": "E7PSZ7MS7C4WI44VTGAKFVTQ"},
    {"name": "VANILLA RUSH", "category": "Frappe Powders", "description": "20lb Bag", "price": 79.38, "square_token": "4IK5SPXQZTUWRWNUYWBOEFPS"},
    {"name": "WHIP CREAM CHARGERS", "category": "Disposables", "description": "50 Chargers", "price": 14.25, "square_token": "KUAJFPKIT2FAPQ7GAXG763BW"},
    {"name": "WHITE CHOCOLATE BLAST", "category": "Frappe Powders", "description": "20lb Bag", "price": 98.94, "square_token": "CJXGAU43AWOKLIZTEVKGN43J"},
    {"name": "WHITE FOOD CONTAINERS LIDS", "category": "Bakery Only", "description": "1 Case", "price": 30.0, "square_token": "75VA2RE23HLPP4GZX3A4IVBN"},
    {"name": "Walnuts (BAKERY)", "category": "Bakery Only", "description": "1 Bag", "price": 20.0, "square_token": "IZV75T7VCKKTWBSE6F3FBCMJ"},
    {"name": "Water Bottles", "category": "Food And Milks", "description": "24 - 16.9oz.", "price": 8.53, "square_token": "2HMQAAXE3VL4GMB5IELMWH5E"},
    {"name": "Whey Protein", "category": "Frappe Powders", "description": "bag", "price": 40.25, "square_token": "VURD327N4WRAHLFEGD5VN4UU"},
    {"name": "Windex", "category": "Cleaning Supplies", "description": "32oz. Bottle", "price": 3.99, "square_token": "2ENG4FSRNQLYUOTGBGKATIQD"},
    {"name": "XANTHAN (2lb Bag)", "category": "Frappe Powders", "description": "Bag 2lb. Up to 3-day lead time.", "price": 29.75, "square_token": "GDMWZDTPV7MXRAYGHP5HPJ6L"},
    {"name": "YEAST(BAKERY)", "category": "Bakery Only", "description": "1 BAG", "price": 6.0, "square_token": "IDOMJHUXDTV7JTWVOL2IXZTQ"},
]


async def seed_supply_catalog(session: AsyncSession) -> None:
    """Seed supply catalog if empty."""
    result = await session.execute(select(SupplyItem).limit(1))
    if result.scalar_one_or_none() is not None:
        return

    for item_data in CATALOG_ITEMS:
        session.add(SupplyItem(
            name=item_data["name"],
            category=item_data["category"],
            description=item_data["description"],
            price=item_data["price"],
            square_token=item_data.get("square_token"),
            is_active=True,
        ))

    await session.commit()
    logger.info("Seeded %d supply catalog items.", len(CATALOG_ITEMS))
